# Controller generated by Typus, use it to extend admin functionality.
class Admin::CredentialsController < Admin::MasterController

  def generate_code
    credential = Credential.find_by_id(params[:id])
    credential.generate_code
    credential.save
    redirect_to :action=>'show', :id=>params[:id]
  end

  def email_code
    credential = Credential.find_by_id(params[:id])
    PurchaseMailer::deliver_purchase_access_code(credential)
    redirect_to :action=>'show', :id=>params[:id]
  end
  
  def generate_speaker_credentials
    presentations = Presentation.find(:all,:conditions=>['status = ? or status = ?','approved','Confirmed'])
    presentations.each do |presentation|
      next unless presentation.email
      credential = Credential.new
      credential.owner = presentation.author
      credential.email = presentation.email
      credential.access = 'Video Delivery'
      credential.access_count = 0
      credential.generate_code
      credential.save
    end
    redirect_to :action=>'index'
  end

  def generate_attendee_credentials
   
    purchases = Purchase.find(:all,:conditions=>['payment_status = ?','paid'])
    purchases.each do |purchase|
      redirect_to :action=>'list' unless purchase.payment_status=='paid'
    
      credential = Credential.new
      credential.owner = purchase.name
      credential.email = purchase.email

      purchased_item_names = purchase.purchased_items.collect {|purchased_item| purchased_item.item.name}
      if purchased_item_names.include?('Conference Pass')
        credential.access = 'Conference Pass'
      end   
      if purchased_item_names.include?('Training Pass')
        credential.access = 'Training Pass'
      end   
      if purchased_item_names.include?('Conference Pass') && purchased_item_names.include?('Training Pass')
        credential.access = 'Video Delivery'
      end
      if purchased_item_names.include?('Video Delivery')
        credential.access = 'Video Delivery'
      end

      credential.access_count = 0
      credential.generate_code
      credential.save
    end
    redirect_to :action=>'index'      
  end
  
  def email_all_codes
    credentials = Credential.all
    credentials.each do |credential|
      PurchaseMailer::deliver_purchase_access_code(credential)
    end
    redirect_to :action=>'index'
  end

end