# Controller generated by Typus, use it to extend admin functionality.
class Admin::PurchasesController < Admin::MasterController

  ##
  # You can overwrite and extend Admin::MasterController with your methods.
  #
  # Actions have to be defined in <tt>config/typus/application.yml</tt>:
  #
  #   Purchase:
  #     actions:
  #       index: custom_action
  #       edit: custom_action_for_an_item
  #
  # And you have to add permissions on <tt>config/typus/application_roles.yml</tt> 
  # to have access to them.
  #
  #   admin:
  #     Purchase: create, read, update, destroy, custom_action
  #
  #   editor:
  #     Purchase: create, read, update, custom_action_for_an_item
  #

  def show_paid
    @purchases = Purchase.find(:all,:conditions=>['payment_status = ?','paid'])
    @items = Item.find(:all)
  end

  def roster
    @purchases = Purchase.find(:all)
    @items = Item.find(:all)
  end


end