# Controller generated by Typus, use it to extend admin functionality.
class Admin::PurchasesController < Admin::MasterController

  ##
  # You can overwrite and extend Admin::MasterController with your methods.
  #
  # Actions have to be defined in <tt>config/typus/application.yml</tt>:
  #
  #   Purchase:
  #     actions:
  #       index: custom_action
  #       edit: custom_action_for_an_item
  #
  # And you have to add permissions on <tt>config/typus/application_roles.yml</tt> 
  # to have access to them.
  #
  #   admin:
  #     Purchase: create, read, update, destroy, custom_action
  #
  #   editor:
  #     Purchase: create, read, update, custom_action_for_an_item
  #

  def show_paid
    @purchases = Purchase.find(:all,:conditions=>['payment_status = ?','paid'])
    @items = Item.find(:all)
  end

  def roster
    @purchases = Purchase.find(:all)
    @items = Item.find(:all)
  end

  def paid_roster
    @purchases = Purchase.find(:all,:conditions=>['payment_status = ?','paid'])
    @items = Item.find(:all)
    render :action=>:roster
  end

  def generate_attendee_credential
    purchase = Purchase.find_by_id(params[:id])
    redirect_to :action=>'list' unless purchase
    redirect_to :action=>'list' unless purchase.payment_status=='paid'
    
    credential = Credential.new
    credential.owner = purchase.name
    credential.email = purchase.email

    purchased_item_names = purchase.purchased_items.collect {|purchased_item| purchased_item.item.name}
    if purchased_item_names.include?('Conference Pass')
      credential.access = 'Conference Pass'
    end   
    if purchased_item_names.include?('Training Pass')
      credential.access = 'Training Pass'
    end   
    if purchased_item_names.include?('Conference Pass') && purchased_item_names.include?('Training Pass')
      credential.access = 'Video Delivery'
    end
    if purchased_item_names.include?('Video Delivery')
      credential.access = 'Video Delivery'
    end

    credential.access_count = 0
    credential.generate_code
    credential.save
    
    redirect_to :controller=>'credentials', :action=>'show', :id=>credential.id
  end
  
end